"""create initial pi-check schema

Revision ID: 573ae4e32a05
Revises: 
Create Date: 2026-06-01 13:20:13.288937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '573ae4e32a05'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aplicacion',
    sa.Column('id_app', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('icono', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=150), nullable=True),
    sa.Column('desarrollador', sa.String(length=255), nullable=True),
    sa.Column('modelo_integracion_actual', sa.String(length=30), nullable=False),
    sa.CheckConstraint("modelo_integracion_actual IN ('HEALTH_CONNECT', 'LEGACY', 'UNKNOWN')", name='ck_aplicacion_modelo_integracion_actual'),
    sa.PrimaryKeyConstraint('id_app')
    )
    op.create_table('indice_privacidad',
    sa.Column('id_indice', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ruta_del_script', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_indice')
    )
    op.create_table('prueba_mastg',
    sa.Column('id_mastg', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('referencia_script_implementacion', sa.Text(), nullable=True),
    sa.Column('categoria_masvs', sa.String(length=100), nullable=True),
    sa.Column('perfil', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_mastg')
    )
    op.create_table('formar_parte',
    sa.Column('id_indice', sa.String(length=100), nullable=False),
    sa.Column('id_mastg', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_indice'], ['indice_privacidad.id_indice'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_mastg'], ['prueba_mastg.id_mastg'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_indice', 'id_mastg')
    )
    op.create_table('version_app',
    sa.Column('id_app', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('version_code', sa.Integer(), nullable=True),
    sa.Column('fecha_version', sa.Date(), nullable=True),
    sa.Column('categoria', sa.String(length=150), nullable=True),
    sa.Column('modelo_integracion', sa.String(length=30), nullable=False),
    sa.Column('ruta_informe_mobsf', sa.Text(), nullable=True),
    sa.Column('hash_mobsf', sa.String(length=128), nullable=True),
    sa.Column('apk_sha256', sa.String(length=64), nullable=True),
    sa.Column('estado_mobsf', sa.String(length=30), nullable=False),
    sa.CheckConstraint("estado_mobsf IN ('NOT_ANALYZED', 'PENDING', 'SUCCESS', 'ERROR')", name='ck_version_app_estado_mobsf'),
    sa.CheckConstraint("modelo_integracion IN ('HEALTH_CONNECT', 'LEGACY', 'UNKNOWN')", name='ck_version_app_modelo_integracion'),
    sa.ForeignKeyConstraint(['id_app'], ['aplicacion.id_app'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_app', 'version')
    )
    op.create_table('evaluar',
    sa.Column('id_app', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('id_mastg', sa.String(length=100), nullable=False),
    sa.Column('resultado', sa.String(length=30), nullable=False),
    sa.Column('ruta_resultado_json', sa.Text(), nullable=True),
    sa.Column('mensaje_error', sa.Text(), nullable=True),
    sa.Column('fecha_ejecucion', sa.DateTime(), nullable=True),
    sa.CheckConstraint("resultado IN ('PASS', 'FAIL', 'ERROR', 'NOT_APPLICABLE', 'NOT_EXECUTED')", name='ck_evaluar_resultado'),
    sa.ForeignKeyConstraint(['id_app', 'version'], ['version_app.id_app', 'version_app.version'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_mastg'], ['prueba_mastg.id_mastg'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_app', 'version', 'id_mastg')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluar')
    op.drop_table('version_app')
    op.drop_table('formar_parte')
    op.drop_table('prueba_mastg')
    op.drop_table('indice_privacidad')
    op.drop_table('aplicacion')
    # ### end Alembic commands ###
